### ISSUE TITLE
Add missing packages

### ISSUE THREAD

**Issue by iamashwin99** [fangohr/octopus-in-spack#67]
Few packages that are already there in spack and require minimal effort include :

- [x] nfft
- [x] pnfft
- [x] berkeleygw
- [ ] sparskit
- [x] etsf-io

**Comment by fangohr** [comment]
For etsf-io, we can perhaps continue https://github.com/fangohr/octopus-in-spack/pull/13 ?

**Comment by iamashwin99** [comment]
I had a look at #13, i felt that it would be easier to add the 3 lines than to deal with the merge conflict that comes when rebasing with that MR.

**Comment by fangohr** [comment]
Just close #13 when you have extract the relevant information and used it elsewhere.
