### ISSUE TITLE
Specify versions of all the dependncies used in the CI

### ISSUE THREAD

**Issue by iamashwin99** [fangohr/octopus-in-spack#75]
It might be a good idea to fully specify the versions of the dependencies we use in our CI.
for eg :
```shell
octopus@12.1%gcc@11.3.0+mpi+netcdf+parmetis+arpack+cgal+pfft+python+likwid+libyaml+elpa+nlopt \
   ^parmetis@4.0.3 \
   ^cgal@5.0.3 \
   ^pfft@1.0.8-alpha \
   ^elpa@2021.11.001 \
   ^nlopt@2.7.0 \
   ^openmpi@4.1.4\
   ^netlib-scalapack@2.1.0 \
   ^fftw@3.3.10+openmp \
   ^hdf5@1.12.2+fortran
```
- It shows users which verions of which depency is tested and expected to work,
- We can mimic the versions of dependencies from easybuild toolchains for comparision.
- Latest versions of some package might not be caches in the spack mirrors ( like libxc6 for eg ) and when their sources disappear (due to website outage for eg ) we will still be able to use the spack mirror ( for eg. libxc@5.2.3 is cached )

**Comment by fangohr** [comment]
Not sure. The link to easybuild toolchains is an MPSD-Octopus-team specific view. 

The purpose of this repo is to provide Octopus through spack for everybody. For everybody, we should see if the compilation works with the versions that spack considers best at the time.
