### ISSUE TITLE
Fix versions of dependencies within the spack package

### ISSUE THREAD

**Issue by iamashwin99** [fangohr/octopus-in-spack#78]
Fix versions of dependencies within the spack package inorder to ensure that the interface of the dependency is consistent with what octopus expects (or was designed with ) . For eg. by default `spack spec octopus` suggests the use of libx6.0.1 which is not supported/tested by octopus developer and they only support libxc5. This was partly also the reason for the previous issue #75 . Other libraries to consider that have known breaking APIs over different versions:

- [ ] libxc
- [ ] cgal and boost
- [ ] berkeleygw@2.1
- [ ] nfft@3.2.24
- [ ] TO BE FOUND

**Comment by iamashwin99** [comment]
5.2.3 is what is suggested ( and tested ) but we should bring this up.

**Comment by iamashwin99** [comment]
From the octopus developers meeting today,
its clear that all versions of libxc 5 greater than libxc 5.1.0 is ok, but libxc6 is not supported.
There used to be a site mentioning the dependencies and their versions at  https://octopus-code.org/wiki/External_Libraries but its now very outdated. Its also not clear which dependencies have which version ranges supported, the version problems I mentioned in this issue ( libxc, berkeleygw, nfft@3.2.24 ) are known but we don't know which other dependencies have similar problem. This can be known only by trial and error.

**Comment by fangohr** [comment]
We have a PR for libxc for this (#81). For the other dependencies, the current settings (mostly no restriction) seem to be fine.
