### ISSUE TITLE
Failure of pipeline (october 2023)

### ISSUE THREAD

**Issue by fangohr** [fangohr/octopus-in-spack#96]
Using this issue to gather debug notes

- Failure at https://github.com/fangohr/octopus-in-spack/actions/runs/6481829767

- digging into this, the following command fails:
```console
user@512fe8a2262b:~/spack$ spack find
==> 0 installed packages
user@512fe8a2262b:~/spack$ spack compilers
==> Available compilers
-- gcc debian11-x86_64 ------------------------------------------
gcc@10.2.1
user@512fe8a2262b:~/spack$ spack spec octopus~mpi+netcdf
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    octopus~mpi+netcdf is unsatisfiable, errors are:
```

**Comment by fangohr** [comment]
Turns out this is originating from the `netcdf` dependency. Somehow [the way we write it in the package](https://github.com/fangohr/octopus-in-spack/blob/1d473d3d26bbd1598a7359609c7810d6c5d1e83c/spack/package.py#L102) does not work well with the new concretizer:
```python
    with when("+mpi"):  # list all the parallel dependencies
        depends_on("netcdf-fortran ^netcdf-c+mpi", when="+netcdf")
```
I can work around this from the command line by using
```
spack spec octopus +mpi+parmetis+arpack+cgal+pfft+pnfft+python+likwid+libyaml+elpa+nlopt+etsf-io+sparskit+berkeleygw+nfft~debug~cuda~metis~scalapack^netcdf-fortran^netcdf-c+mpi 
```
instead of 
```
spack spec octopus +mpi+parmetis+arpack+cgal+pfft+pnfft+python+likwid+libyaml+elpa+nlopt+etsf-io+sparskit+berkeleygw+nfft~debug~cuda~metis~scalapack+netcdf
```

I will try to change the Dockerfile in this repo to use the above fix.

What really should do though (new issue?) is to improve the spack package file for Octopus. This may need the help of the spack team.

**Comment by iamashwin99** [comment]
I can confirm that the spec fails with a not so helpful error message. I'm curious however bout how you debugged that it was the netcdf one causing the error.

**Comment by fangohr** [comment]
How I found out: It fails at computing the spec. So I tested the spec with all the variants (which included netcdf), and it fails. Then I tested without any variants, and it can compute the spec (let's call that a 'pass'). I then removed one of the variants after another, and attempted to compute the spec for all. Until I removed the one that created a problem (netcdf). I deleted variants from the back - of course netcdf was last. With a bit more focus one could have used a bisection approach and reduce the number of attempts to compute the spec. 

I did a bit more testing to see if perhaps a combination of packages was creating the problem but it didn't look like it. Once I looked into the `package.py` file it seems likely that netcdf caused the problem because the dependency specification was different from all others.

**Comment by iamashwin99** [comment]
Ah! Thats the most obvious way but extremely tedious.
Im wondering if in the CI we can somehow ask spack to test all possible combinations of variants (or atleast a subset ) in a simple way (less code). 
This shouldn't take quite long as the specs are cached and incrementally adding variants should perhaps not  take longer than specing altogether ( or at least should be comparable)

**Comment by fangohr** [comment]
Can you approve it (or review it)? Would be good to request this change upstream before the next spack release ;-).

**Comment by fangohr** [comment]
No need for a more systematic test: this kind of failure is unlikely, and the existing CI told us that something was broken  (so it worked).
